name: GitHub CI

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
      - release/*

env:
  MAIN_PYTHON_VERSION: '3.10'
  PACKAGE_NAME: 'ansys-mechanical-env'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: PyAnsys code style checks
        uses: ansys/actions/code-style@v7
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false

  doc-style:
    name: Documentation Style Check
    runs-on: ubuntu-latest
    steps:
      - name: PyAnsys documentation style checks
        uses: ansys/actions/doc-style@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  smoke-tests:
    name: Build and Smoke tests
    runs-on: ubuntu-latest
    needs: [style]
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        should-release:
          - ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags') }}
    steps:
      - name: Build wheelhouse and perform smoke test
        uses: ansys/actions/build-wheelhouse@v7
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          operating-system: ubuntu-latest
          python-version: ${{ matrix.python-version }}

  changelog-check:
    name: Changelog Update Check
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CHANGELOG_TOKEN }}

      - uses: dangoslen/dependabot-changelog-helper@v3
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          activationLabel: 'dependabot'
          changelogPath: './CHANGELOG.md'

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          commit_message: "Updated Changelog"

      - name: Get all doc files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            doc:
              - 'CHANGELOG.md'

      - name: Check Changelog Edited
        run: |
          if [[ "${{ steps.changed-files-yaml.outputs.doc_all_changed_files }}" == "CHANGELOG.md" ]]; then
              echo "CHANGELOG.md was updated."
          elif [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
              echo "CHANGELOG.md was autoupdated... Workflow will trigger."
          else
              echo "Please update CHANGELOG.md before merging the pull request."
              exit 1
          fi

  tests:
    name: Unit tests and coverage
    runs-on: ubuntu-latest
    needs: [smoke-tests]
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        containers: ['23.2.0', '24.1.0', '24.2.0', '25.1.0']
    container:
      image: ghcr.io/ansys/mechanical:${{ matrix.containers }}
      options: --entrypoint /bin/bash

    steps:
      - uses: actions/checkout@v4
      - name: Set up python and pip
        run: |
          apt update
          apt install software-properties-common -y
          add-apt-repository ppa:deadsnakes/ppa -y
          apt install python${{ matrix.python-version }} -y
          ln -s /usr/bin/python${{ matrix.python-version }} /usr/bin/python
          apt install python${{ matrix.python-version }}-venv -y

      - name: Install pip for >3.8
        run: |
          python -m ensurepip --default-pip

      - name: Upgrade pip and install packages for testing
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements/requirements_tests.txt

      - name: Pytests and coverage
        run: |
          pip3 install .
          pytest -v --cov=ansys.mechanical.env

  doc-build:
    name: Documentation building
    needs: [style, doc-style]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          mkdir -p doc/_build/html
          mkdir -p doc/_build/latex
          touch doc/_build/html/doc.txt
          touch doc/_build/latex/doc.pdf

      - name: Upload HTML Documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation-html
          path: doc/_build/html/doc.txt
          retention-days: 7

      - name: Upload PDF Documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdf
          path: doc/_build/latex/doc.pdf
          retention-days: 7

  package:
    name: Build package
    needs: [tests, doc-build]
    runs-on: ubuntu-latest
    steps:
      - name: Build library source and wheel artifacts
        uses: ansys/actions/build-library@v7
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  release:
    name: Release project
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [package]
    runs-on: ubuntu-latest
    steps:
      - name: Release to the public PyPI repository
        uses: ansys/actions/release-pypi-public@v7
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.PYPI_TOKEN }}

      - name: Release to GitHub
        uses: ansys/actions/release-github@v7
        with:
          library-name: ${{ env.PACKAGE_NAME }}
